
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[215] =
    {   0,
        0,    0,   91,   89,   84,   85,   83,   73,   89,   63,
       67,   89,   75,   78,   61,   59,   66,   60,   72,   62,
       34,   65,   64,   81,   68,   82,   74,   33,   76,   79,
       71,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   77,   70,   80,   69,
        0,   46,    0,   37,   51,   47,   56,    0,   49,   39,
       52,   40,   53,   38,    0,   88,   50,    0,   34,   41,
       43,   45,   44,   42,   33,   57,   33,   33,   33,   33,
       33,   33,    8,   33,   33,   33,   33,   33,   33,   16,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   58,   48,   86,   36,    0,    0,   88,   35,   54,
       55,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   14,   33,   17,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       87,    1,   33,    3,    4,   33,   33,   33,   33,   10,
       11,   33,   33,   15,   18,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   30,   33,   33,    2,
        5,   33,   33,   33,   33,   13,   33,   33,   21,   33,
       33,   33,   33,   33,   33,   28,   33,   33,   32,   33,
       33,    9,   12,   33,   20,   22,   23,   24,   25,   26,

       33,   33,   33,   33,    7,   33,   27,   33,   33,    6,
       19,   29,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   26,   25,   25,   25,   25,   25,   25,   25,
       27,    1,   28,   29,    1,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    1,    1,
        1,    1,    1,    1,    5,    5,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[220] =
    {   0,
        0,    0,  237,  238,  238,  238,  238,   53,  230,  213,
       51,    0,  238,  238,  212,   47,  238,   48,  238,   50,
       48,  238,  238,   55,  211,   56,  238,    0,  238,  238,
      210,  183,  185,   31,   46,   41,   42,  186,   49,  185,
      193,   49,  174,  183,  181,  186,  238,   43,  238,  238,
      196,  238,  215,  238,  238,  238,  238,  211,  238,  238,
      238,  238,  238,  238,  207,    0,  238,  200,   72,  195,
      238,  238,  238,  194,    0,  238,  168,  180,  167,  182,
      169,  175,  161,  162,  159,  159,  162,  159,  156,    0,
      155,  159,   57,  157,   58,   65,  161,  154,   59,   62,

      159,  238,  238,  238,  238,  184,  178,    0,  176,  238,
      238,  150,  162,  157,  145,   60,  159,  157,  153,  145,
      151,  154,    0,  140,    0,  146,  143,  132,  134,  136,
      143,  129,  127,  127,  139,  129,  133,  137,  139,  128,
      238,    0,  128,    0,    0,  119,  127,  116,  123,    0,
        0,  117,  114,    0,    0,  114,  114,  111,  123,  113,
      117,  122,  121,  119,  109,  114,    0,  102,  114,    0,
        0,  105,  106,  111,  102,    0,   96,  100,    0,  108,
      105,  107,   91,  100,  102,    0,   93,   96,    0,   85,
       85,    0,    0,   97,    0,    0,    0,    0,    0,    0,

       95,   95,   85,   87,    0,   64,    0,   75,   69,    0,
        0,    0,    0,  238,  111,   96,  113,  118,  123
    } ;

static yyconst flex_int16_t yy_def[220] =
    {   0,
      214,    1,  214,  214,  214,  214,  214,  214,  215,  214,
      214,  216,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  217,  214,  214,
      214,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  214,  214,  214,  214,
      214,  214,  215,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  218,  219,  214,  214,  214,  214,
      214,  214,  214,  214,  217,  214,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,

      217,  214,  214,  214,  214,  218,  214,  219,  214,  214,
      214,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      214,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,

      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,    0,  214,  214,  214,  214,  214
    } ;

static yyconst flex_int16_t yy_nxt[296] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   28,   39,   28,   40,
       28,   28,   28,   28,   41,   42,   43,   44,   45,   46,
       28,   28,   28,   47,   48,   49,   50,   51,   56,   60,
       79,   65,   62,   68,  102,   69,   66,   80,   61,   63,
       64,   67,   57,   81,   52,   70,   71,   73,   74,   82,
       84,   87,   85,   90,   88,   94,   95,   68,   83,   69,
       91,   86,  127,  130,  132,   96,  136,  103,   97,  138,

       58,  139,  213,  128,  137,  146,  147,  212,  211,  133,
      131,   53,   53,   53,   53,   53,   75,   75,  106,  106,
      210,  106,  106,  108,  209,  108,  108,  108,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  145,
      144,  143,  142,  109,  141,  107,  140,  135,  134,  129,

      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  107,  105,
       54,  104,  101,  100,   99,   98,   93,   92,   89,   78,
       77,   76,   72,   59,   55,   54,  214,    3,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214

    } ;

static yyconst flex_int16_t yy_chk[296] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,   11,   16,
       34,   20,   18,   21,   48,   21,   20,   34,   16,   18,
       18,   20,   11,   34,    8,   24,   24,   26,   26,   35,
       36,   37,   36,   39,   37,   42,   42,   69,   35,   69,
       39,   36,   93,   95,   96,   42,   99,   48,   42,  100,

      216,  100,  209,   93,   99,  116,  116,  208,  206,   96,
       95,  215,  215,  215,  215,  215,  217,  217,  218,  218,
      204,  218,  218,  219,  203,  219,  219,  219,  202,  201,
      194,  191,  190,  188,  187,  185,  184,  183,  182,  181,
      180,  178,  177,  175,  174,  173,  172,  169,  168,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      153,  152,  149,  148,  147,  146,  143,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  124,  122,  121,  120,  119,  118,  117,  115,
      114,  113,  112,  109,  107,  106,  101,   98,   97,   94,

       92,   91,   89,   88,   87,   86,   85,   84,   83,   82,
       81,   80,   79,   78,   77,   74,   70,   68,   65,   58,
       53,   51,   46,   45,   44,   43,   41,   40,   38,   33,
       32,   31,   25,   15,   10,    9,    3,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../lexer/cLexer.l"
/*
File: cLexer.l
Created: September 27, 2015
Last Modified: October 28, 2015
Class: CS 460 (Compiler Construction)

This is the input file to Flex that will be used in the front end of our
compiler. 

The lexer is responsible for two main tasks:
1. Scan for tokens and pass these tokens to the parser for syntax analysis.
2. Place as much information into the symbol table as possible. Some of tihis
responsibility is left to the parser. 

Tokens have been declared by Bison and are included in the file 
"cParser.tab.h."
*/
/* lexer definitions */
#line 21 "../lexer/cLexer.l"
	/* includes */
	#include <iostream>
	#include <string>
	#include <climits>
	#include <stdlib.h>
	#include <cstdlib>
	#include <fstream>
	#include <algorithm>
	#include "Escape_Sequences_Colors.h"
	#include "../parser/cParser.tab.h"
	#include "../classes/symbolTable.h"


	#define MAX_ID_LEN 64
	#define MAX_STR_LEN 256

	/* externs */
	extern bool LFLAG; 
	extern bool YFLAG;
	extern std::ofstream outL; 

	extern std::ofstream outY; 
	extern void yyerror(const char* errorMsg);


	/* variables */
	node* nodeTemp = NULL; 
	bool inInsertMode = true; // false => "lookup mode"
	int colPosition = 0;
	int tabCount = 0; 
	symbolTable table;
	std::string currentSourceCodeLine = ""; 
	extern std::vector<std::string> sourceCode;
	std::vector<int> typeSpecifiers;   
	bool endline = false;
	bool tab = false;
	bool space = false;
	int numStar = 0;
	bool linePrinted = false;

	/* functions */
	int isValidType(std::vector<int> type);
/* token definitions */
/* tell flex to read only one input file - THIS COULD CHANGE */
/* rules and actions */
#line 663 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 79 "../lexer/cLexer.l"

 endline = false;
 space = false;
 /*
 if( (LFLAG || YFLAG) && !linePrinted){
		
		if(LFLAG){
			outL << std::endl << "=================================================================" << std::endl;
			outL << "Line #" << yylineno << ": " << std::endl;
			outL << sourceCode[yylineno-1] << std::endl;
		}
		if(YFLAG){
			outY << std::endl <<"=================================================================" << std::endl;
			outY << "Line #" << yylineno << ": " << std::endl;
			outY << sourceCode[yylineno-1] << std::endl;
		}
		linePrinted = true;
 }*/

#line 870 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 215 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 238 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 98 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< AUTO >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return AUTO; 
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 106 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< BREAK >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return BREAK; 
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 114 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << " < CASE >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return CASE; 
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 122 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< CHAR >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					typeSpecifiers.push_back(CHAR_T); 
					return CHAR; 
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 131 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< CONST >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return CONST; 
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 139 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< CONTINUE >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return CONTINUE; 
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 147 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< DEFAULT >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return DEFAULT; 
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 155 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< DO >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return DO; 
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 163 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< DOUBLE >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					typeSpecifiers.push_back(DOUBLE_T);
					return DOUBLE; 
				}	
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 172 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ELSE >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return ELSE; 
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 180 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ENUM >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return ENUM; 
				}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 188 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< EXTERN >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return EXTERN; 
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 196 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< FLOAT >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					typeSpecifiers.push_back(FLOAT_T);
					return FLOAT; 
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 205 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< FOR >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return FOR; 
				}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 213 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< GOTO >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return GOTO; 
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 221 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< IF >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return IF;  
				}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 229 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< INT >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					typeSpecifiers.push_back(INT_T);
					return INT; 	
				}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 238 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< LONG >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					typeSpecifiers.push_back(LONG_T);
					return LONG; 
				}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 247 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< REGISTER >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return REGISTER; 
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 255 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< RETURN >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return RETURN; 
				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 263 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< SHORT >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					typeSpecifiers.push_back(SHORT_T);
					return SHORT; 
				}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 272 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< SIGNED >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return SIGNED; 
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 280 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< SIZEOF >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return SIZEOF; 
				}	
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 288 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< STATIC >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return STATIC; 
				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 296 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< STRUCT >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return STRUCT; 
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 304 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< SWITCH >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return SWITCH; 
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 312 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< TYPEDEF >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return TYPEDEF; 
				}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 320 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< UNION >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return UNION; 
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 328 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< UNSIGNED >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return UNSIGNED; 
				}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 336 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< VOID >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					typeSpecifiers.push_back(VOID_T);
					return VOID; 
				}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 345 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< VOLATILE >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return VOLATILE; 
				}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 353 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< WHILE >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return WHILE; 
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 361 "../lexer/cLexer.l"
{ 
					if(LFLAG){
						outL << "< IDENTIFIER >";
					}

					if(yyleng > MAX_ID_LEN){
						std::cout << COLOR_MAGENTA_NORMAL << "WARNING:" << COLOR_NORMAL << " Identifier ";
						std::cout << COLOR_NORMAL << COLOR_BOLD_RED_NORMAL << yytext << COLOR_NORMAL;
						std::cout << " exceeds maximum name length" << std::endl;
					}

					std::string newEntry(yytext);
					currentSourceCodeLine += newEntry;
					symbolTableEntry* searchResult = NULL;
					int level;

					if(typeSpecifiers.size()==0){
						inInsertMode = false;
					}

					if (inInsertMode) {
						searchResult = table.searchTopOfStack(newEntry);
						if (searchResult != NULL) {
							char lineNum[15];
							sprintf(lineNum, "%d", yylineno);
							std::cout << COLOR_NORMAL;
							std::cout << COLOR_CYAN_NORMAL << "ERROR:" << COLOR_NORMAL << " Redeclaration of Variable " << COLOR_BOLD << COLOR_RED_NORMAL << newEntry << COLOR_NORMAL << " declared here: \n";
							std::cout << COLOR_GREEN_NORMAL << "\tLine " << (std::string)lineNum << ": " << COLOR_NORMAL << COLOR_WHITE_NORMAL << sourceCode[yylineno - 1] << COLOR_NORMAL << "\n";
							sprintf(lineNum, "%d", searchResult->getLineNumber());
							std::cout << COLOR_NORMAL;
							std::cout << "Previously declared here: \n";
							std::cout << COLOR_GREEN_NORMAL << "\tLine " << (std::string)lineNum << ": " << COLOR_NORMAL << COLOR_WHITE_NORMAL << sourceCode[searchResult->getLineNumber() - 1] << COLOR_NORMAL << "\n";
							yyerror("");
						}

						if( (searchResult = table.searchForSymbol(newEntry, level)) != NULL) {
							char lineNum[15];
							sprintf(lineNum, "%d", yylineno);
							std::cout << COLOR_NORMAL;
							std::cout << COLOR_MAGENTA_NORMAL << "WARNING:" << COLOR_NORMAL << " Variable " << COLOR_BOLD << COLOR_RED_NORMAL <<  newEntry << COLOR_NORMAL << " declared here: \n";
							std::cout << COLOR_GREEN_NORMAL << "\tLine " << (std::string)lineNum << ": " << COLOR_NORMAL << COLOR_WHITE_NORMAL << sourceCode[yylineno - 1] << COLOR_NORMAL << "\n";
							sprintf(lineNum, "%d", searchResult->getLineNumber());
							std::cout << COLOR_NORMAL;
							std::cout << "Shadows variable previously declared here: \n";
							std::cout << COLOR_GREEN_NORMAL << "\tLine " << (std::string)lineNum << ": " << COLOR_NORMAL << COLOR_WHITE_NORMAL << sourceCode[searchResult->getLineNumber() - 1] << COLOR_NORMAL << "\n";
							searchResult->setNumPtrs(numStar);
							numStar = 0;
							if(!searchResult->setIdentifierType(typeSpecifiers) && (typeSpecifiers.size() != 0)){
								char lineNum[15];
								sprintf(lineNum, "%d", yylineno);
								std::cout << COLOR_NORMAL;
								std::cout << COLOR_CYAN_NORMAL << "ERROR:" << COLOR_NORMAL << " Invalid data type used here:\n";
								std::cout << COLOR_GREEN_NORMAL << "\tLine #" << (std::string)lineNum << (std::string)": " << COLOR_NORMAL;
								std::cout << COLOR_WHITE_NORMAL << sourceCode[yylineno-1] << "\n";
								std::cout << COLOR_NORMAL;
								yyerror("");
							}
							searchResult = table.insertNewSymbol(newEntry, yylineno);
							yylval.n = new node();
							yylval.n->val._ste = searchResult;
							yylval.n->valType = STE_T;
							typeSpecifiers.clear();						
							return IDENTIFIER;
						}

						else{
							searchResult = table.insertNewSymbol(newEntry, yylineno);
							searchResult->setNumPtrs(numStar);
							numStar = 0;

							if(!searchResult->setIdentifierType(typeSpecifiers) && (typeSpecifiers.size() != 0)){
								char lineNum[15];
								sprintf(lineNum, "%d", yylineno);
								std::cout << COLOR_NORMAL;
								std::cout << COLOR_CYAN_NORMAL << "ERROR:" << COLOR_NORMAL << " Invalid data type used here:\n";
								std::cout << COLOR_GREEN_NORMAL << "\tLine #" << (std::string)lineNum << (std::string)": " << COLOR_NORMAL;
								std::cout << COLOR_WHITE_NORMAL << sourceCode[yylineno-1] << COLOR_NORMAL << "\n";
								yyerror("");
							} 
							colPosition += strlen(yytext);
							yylval.n = new node();
							yylval.n->val._ste = searchResult;
							yylval.n->valType = STE_T;
							typeSpecifiers.clear();			
							return IDENTIFIER;
						}
					}
					else{
						searchResult = table.searchForSymbol(newEntry, level);
						if(searchResult == NULL){
							char lineNum[15];
							sprintf(lineNum, "%d", yylineno);
							std::cout << COLOR_NORMAL;
							std::cout << COLOR_CYAN_NORMAL << "ERROR: " << COLOR_NORMAL << COLOR_BOLD_RED_NORMAL << newEntry << COLOR_NORMAL << " was not declared in this scope." << "\n";
							std::cout << COLOR_GREEN_NORMAL << "\tLine #" << (std::string)lineNum << (std::string)": " << COLOR_NORMAL;
							std::cout << COLOR_WHITE_NORMAL << sourceCode[yylineno-1] << COLOR_NORMAL << "\n";
							yyerror("");
						}
						else{
							yylval.n = new node();
							yylval.n->val._ste = searchResult;
							yylval.n->valType = STE_T;
							return IDENTIFIER;
						}
					}
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 467 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< INTEGER_CONSTANT >";
					}
					std::string strTemp(yytext);
					std::string MAX_NUM = "18446744073709551615";

					if( strTemp.length() > MAX_NUM.length() ){
						char lineNum[15];
						sprintf(lineNum, "%d", yylineno);
						std::cout << COLOR_NORMAL;
						std::cout << COLOR_CYAN_NORMAL << "ERROR: ";
						std::cout << COLOR_NORMAL << COLOR_BOLD_RED_NORMAL << strTemp << COLOR_NORMAL << " exceeds maximum number value.\n";
						std::cout << COLOR_GREEN_NORMAL << "\tLine #" << (std::string)lineNum << (std::string)": " << COLOR_NORMAL;
						std::cout << COLOR_WHITE_NORMAL << sourceCode[yylineno-1] << COLOR_NORMAL << "\n";
						yyerror("");	
					}
					else if(strTemp.length() == MAX_NUM.length()){
						if( strTemp > MAX_NUM ){
						char lineNum[15];
						sprintf(lineNum, "%d", yylineno);
						std::cout << COLOR_NORMAL;
						std::cout << COLOR_CYAN_NORMAL << "ERROR: ";
						std::cout << COLOR_NORMAL << COLOR_BOLD_RED_NORMAL << strTemp << COLOR_NORMAL << " exceeds maximum number value.\n";
						std::cout << COLOR_GREEN_NORMAL << "\tLine #" << (std::string)lineNum << (std::string)": " << COLOR_NORMAL;
						std::cout << COLOR_WHITE_NORMAL << sourceCode[yylineno-1] << COLOR_NORMAL << "\n";
						yyerror("");							}
					}
					
   					currentSourceCodeLine += strTemp;
   					nodeTemp = new node;
   					nodeTemp->valType = LONG_LONG_T;
   					nodeTemp->val._num = atoll(yytext);
					yylval.n = nodeTemp;
					nodeTemp = NULL;  
					return INTEGER_CONSTANT; 						
				}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 504 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< FLOATING_CONSTANT >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					nodeTemp = new node;
   					nodeTemp->valType = LONG_DOUBLE_T;
   					nodeTemp->val._dec = strtold(yytext, NULL);
					yylval.n = nodeTemp;
					nodeTemp = NULL;  
					return FLOATING_CONSTANT; 		
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 517 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< CHARACTER_CONSTANT >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
   					nodeTemp = new node;
   					nodeTemp->valType = CHAR_T;
   					nodeTemp->val._char = yytext[1];
					yylval.n = nodeTemp;
					nodeTemp = NULL;  
					return CHARACTER_CONSTANT; 		
				}
	YY_BREAK
/* don't know what this is 
{
						if(LFLAG){
						outL << "< ENUMERATION_CONSTANT >";
					}
					return ENUMERATION_CONSTANT; 		
}
			*/
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 538 "../lexer/cLexer.l"
{
					
					if(LFLAG){
						outL << "< STRING_LITERAL > ";
					}
					if( yyleng > MAX_STR_LEN ){
						std::cout << COLOR_MAGENTA_NORMAL << "WARNING:" << COLOR_NORMAL << " String exceeds maximum string length" << std::endl;
						yyerror("");
					}

   					nodeTemp = new node;
   					nodeTemp->valType = STR_T;
   					strncpy(nodeTemp->val._str, yytext, yyleng);
					nodeTemp->val._str[yyleng]='\0';
					yylval.n = nodeTemp;
					nodeTemp = NULL;  
					return STRING_LITERAL;
				}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 556 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< -> > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return PTR_OP;
				}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 564 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ++ > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return INC_OP;
				}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 572 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< -- > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return DEC_OP;
				}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 580 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< << > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return LEFT_OP;
				}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 588 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< -> > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return RIGHT_OP;
				}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 596 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< <= > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return LE_OP;
				}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 604 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< >= > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return GE_OP;
				}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 612 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< == > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return EQ_OP;
				}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 620 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< != >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return NE_OP;
				}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 628 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< && >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return AND_OP;
				}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 636 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< || >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return OR_OP;
				}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 644 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< *= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return MUL_ASSIGN;
				}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 652 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< /= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return DIV_ASSIGN;
				}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 660 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< %= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return MOD_ASSIGN;
				}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 668 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< += >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return ADD_ASSIGN;
				}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 676 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< -= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return SUB_ASSIGN;
				}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 684 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< <<= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return LEFT_ASSIGN;
				}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 692 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< >>= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return RIGHT_ASSIGN;
				}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 700 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< &= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return AND_ASSIGN;
				}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 708 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ^= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return XOR_ASSIGN;
				}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 716 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< |= >";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return XOR_ASSIGN;
				}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 724 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< + > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return PLUS;
				}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 732 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< - > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return MINUS;
				}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 740 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< * > ";
					}
					numStar++;
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return MULT;
				}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 749 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< / > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return DIV;
				}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 757 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< % > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return MOD;
				}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 765 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ; > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return SEMI;
				}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 773 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< : > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return COLON;
				}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 781 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< , > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return COMMA;
				}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 789 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< & > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return AMP;
				}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 797 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< = > ";
					}					
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return ASSIGN;
				}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 805 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ~ > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return TILDE;
				}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 813 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< | > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return PIPE;
				}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 821 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ^ > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return CARROT;
				}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 829 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< . > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return DOT;
				}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 837 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ! > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return BANG;
				}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 845 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ? > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return QUESTION;
				}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 853 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ( > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return LPAREN;
				}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 861 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< [ > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return LBRACK;
				}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 869 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< { > ";
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return LCURL;
				}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 877 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ) > ";
					} 
					if(isValidType(typeSpecifiers) == -1 && (typeSpecifiers.size() != 0)){
							char lineNum[15];
							sprintf(lineNum, "%d", yylineno);
							std::cout << COLOR_CYAN_NORMAL << "ERROR:" << COLOR_NORMAL << " Invalid data type used here:\n";
							std::cout << COLOR_GREEN_NORMAL << "\tLine #" << (std::string)lineNum << (std::string)": " << COLOR_NORMAL;
							std::cout << COLOR_WHITE_NORMAL << sourceCode[yylineno-1];
					   		std::cout << COLOR_NORMAL;
							yyerror("");

					}

					typeSpecifiers.clear();
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;

					return RPAREN;
				}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 898 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< ] > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return RBRACK;
				}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 906 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< } > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return RCURL;
				}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 914 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< < > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return LTHAN;
				}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 922 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< > > ";
					} 
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
					return GTHAN;
				}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 930 "../lexer/cLexer.l"
{
					space = true;
					colPosition += yyleng;
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
				}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 936 "../lexer/cLexer.l"
{

					colPosition ++;
					currentSourceCodeLine += ' ';
				}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 941 "../lexer/cLexer.l"
{

					//sourceCode.push_back(currentSourceCodeLine);
					currentSourceCodeLine = "";  
					yylineno++; 
					colPosition = 0;
					endline = true;
					if(LFLAG){
						outL << std::endl << "=================================================================" << std::endl;
						outL << "Line #" << yylineno << ": " << std::endl;
						outL << sourceCode[yylineno-1] << std::endl;
					}
					if(YFLAG){
						outY << std::endl <<"=================================================================" << std::endl;
						outY << "Line #" << yylineno << ": " << std::endl;
						outY << sourceCode[yylineno-1] << std::endl;
					}
				}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 959 "../lexer/cLexer.l"
{outY << "READ !!S" << std::endl;
					table.writeToScreen(); 
				}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 963 "../lexer/cLexer.l"
{	
					std::string comment(yytext);
					yylineno += std::count(comment.begin(), comment.end(), '\n');

				}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 968 "../lexer/cLexer.l"
{
				}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 970 "../lexer/cLexer.l"
{
						std::string token(yytext);
						char temp[256];
						char lineNum[15];
						strcpy(temp, sourceCode[yylineno-1].c_str());
						sprintf(lineNum, "%d", yylineno);
						int iter = 0;
						std::cout << COLOR_CYAN_NORMAL << "ERROR:" << COLOR_NORMAL << "Unexpected character " << COLOR_NORMAL << COLOR_BOLD_RED_NORMAL << token << COLOR_NORMAL;
						std::cout << " here:" << (std::string)"\n";
						while(temp[iter] != '\0')
						{
							if( iter == 0 ){
								std::cout << COLOR_GREEN_NORMAL << "\tLine #" << (std::string)lineNum << (std::string)": " << COLOR_NORMAL;
							}
							if(temp[iter] == yytext[0])
							{
								std::cout << COLOR_NORMAL << COLOR_BOLD_RED_NORMAL << token << COLOR_NORMAL;
							}
							else{
								std::cout << COLOR_WHITE_NORMAL << temp[iter];
							}
							iter++;
						}
						std::cout << COLOR_NORMAL;
						yyerror("");
				}		
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 996 "../lexer/cLexer.l"
ECHO;
	YY_BREAK
#line 2214 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 215 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 215 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 214);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 996 "../lexer/cLexer.l"



/* user code */

/*
Function: isValidType(std::vector<int> type)

Description: This function will check to see if a supplied vector of 
tokens matches any of the allowable datatypes in C. If the supplied vector
contains an allowable data type, the function will return the enumerated
integer of the associated data type. If the incoming vector contains tokens
in an invalid order, the function will return -1. 

Parameters:
std::vector<int> type: This is the incoming vector of tokens that will be
used to determine if the compiler has encountered a valid datatype. 
*/
int isValidType(std::vector<int> type){
	// populate the map for each symbol table entry
	// ex: "long long, long int, etc."
	std::map<std::vector<int>, int> validTypes; 
	std::map<std::vector<int> , int>::iterator mapItr;
	std::vector<int> validType;

	// char
	validType.push_back(CHAR_T);
	validTypes.insert(pair(validType, CHAR_T));
	validType.clear();

	// double
	validType.push_back(DOUBLE_T);
	validTypes.insert(pair(validType, DOUBLE_T));
	validType.clear();

	// float
	validType.push_back(FLOAT_T);
	validTypes.insert(pair(validType, FLOAT_T));
	validType.clear();

	// int 
	validType.push_back(INT_T);
	validTypes.insert(pair(validType, INT_T));
	validType.clear();

	// long
	validType.push_back(LONG_T);
	validTypes.insert(pair(validType, LONG_T));
	validType.clear();

	// long int
	validType.push_back(LONG_T);
	validType.push_back(INT_T);
	validTypes.insert(pair(validType, LONG_T));
	validType.clear();

	// long long
	validType.push_back(LONG_T);
	validType.push_back(LONG_T);
	validTypes.insert(pair(validType, LONG_LONG_T));
	validType.clear();	

	// long long int
	validType.push_back(LONG_T);
	validType.push_back(LONG_T);
	validType.push_back(INT_T);
	validTypes.insert(pair(validType, LONG_LONG_T));
	validType.clear();

	// long double
	validType.push_back(LONG_T);
	validType.push_back(DOUBLE_T);
	validTypes.insert(pair(validType, LONG_DOUBLE_T));
	validType.clear();

	// short
	validType.push_back(SHORT_T);
	validTypes.insert(pair(validType, SHORT_T));
	validType.clear();	

	// short int
	validType.push_back(SHORT_T);
	validType.push_back(INT_T);
	validTypes.insert(pair(validType, SHORT_T));
	validType.clear();	

	// void
	validType.push_back(VOID_T);
	validTypes.insert(pair(validType, VOID_T));
	validType.clear();	

	// search for the vector in the predefined map of data types
	mapItr = validTypes.find(type);
	if(mapItr != validTypes.end()){
		// if found, return the enumerated integer used to identify the 
		// data type
		return mapItr->second;
	}

	// if unable to locate, indicate to the caller. 
	return -1;
}

